name: threat-modeling-dashboard
region: nyc

services:
  - name: api
    dockerfile_path: Dockerfile
    github:
      repo: YOUR_GITHUB_USERNAME/llm-powered-threat-modelling
      branch: main
      deploy_on_push: true
    http_port: 3001
    instance_count: 1
    instance_size_slug: basic-xxs
    health_check:
      http_path: /health
      initial_delay_seconds: 10
      period_seconds: 30
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3001"
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${db.DATABASE_URL}
      - key: CORS_ORIGINS
        scope: RUN_TIME
        value: ${APP_URL}
      # LLM Provider - uncomment one
      - key: LLM_PROVIDER
        scope: RUN_TIME
        value: openai
      - key: OPENAI_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: OPENAI_MODEL
        scope: RUN_TIME
        value: gpt-4o
      # Or use Anthropic:
      # - key: LLM_PROVIDER
      #   scope: RUN_TIME
      #   value: anthropic
      # - key: ANTHROPIC_API_KEY
      #   scope: RUN_TIME
      #   type: SECRET
      # - key: ANTHROPIC_MODEL
      #   scope: RUN_TIME
      #   value: claude-sonnet-4-20250514

      # Optional: S3 Storage
      # - key: STORAGE_PROVIDER
      #   value: s3
      # - key: S3_BUCKET
      #   scope: RUN_TIME
      # - key: S3_REGION
      #   scope: RUN_TIME
      # - key: AWS_ACCESS_KEY_ID
      #   scope: RUN_TIME
      #   type: SECRET
      # - key: AWS_SECRET_ACCESS_KEY
      #   scope: RUN_TIME
      #   type: SECRET

      # Optional: JIRA Integration
      # - key: JIRA_HOST
      #   scope: RUN_TIME
      # - key: JIRA_EMAIL
      #   scope: RUN_TIME
      # - key: JIRA_API_TOKEN
      #   scope: RUN_TIME
      #   type: SECRET

databases:
  - name: db
    engine: PG
    version: "16"
    size: db-s-dev-database
    num_nodes: 1
